# Generated by Django 3.1 on 2020-10-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('feature', models.CharField(max_length=200)),
                ('digital', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
