# Generated by Django 3.1 on 2020-10-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryitem',
            name='image_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
