# Generated by Django 3.1 on 2020-10-21 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_secondbanner_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactsection',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
